### ISSUE TITLE
Need the 64 bit release

### ISSUE THREAD

**Issue by AlexRozen** [thomas694/finddupe#1] opened 2023-08-20 14:13 UTC
It seems that published version is limited with files not greater than 2GiB inside the call of function _stat. 
Simply rebuilding project to the x64 target got another problems, but I'm not a C developer, so I need some help with it.

P.S. Got x64 version 1.25 from original repo. Seems to be working for me. Also it gives more verbose output for file hardliking in non-verbose mode (source and target paths are printed, instead of the only "Created hardlink" message in this version)

**Comment by thomas694** [comment] 2023-08-21 17:51
Obviously I haven't used it with such large files yet. The problem is fixed in the new version.
In addition, the source and target paths of the hard link are displayed again.

**Comment by AlexRozen** [comment] 2023-08-21 18:24
Great! Thanks a lot. Seems to be working. Checked via the already deduplicated folder, but I think that API call must be the same.

**Comment by thomas694** [comment] 2023-08-21 23:27
> but I think that API call must be the same.

Still something wrong?

**Closed as completed** 2023-08-22 15:30 UTC
